### ISSUE TITLE
TODO v1

### ISSUE THREAD

**Issue by ENAC-Robotique** [KirrimK/graph2strat#4]
Forget everything in #3.
What we really want is a `do()` method on each state.
This method run at least once, and should be called in a loop until a guard become True.
The G2S main loop should be like:
```
self.stm_statemachine.do()
self.stm_statemachine.check_transitions()
```

**Comment by KirrimK** [comment]
Resolved with version 1.5.0: https://github.com/KirrimK/graph2strat/releases/tag/1.5.0
